In [52]:
import os
import requests
from dotenv import load_dotenv

load_dotenv()  # loads variables from .env

api_key = os.getenv("API_KEY")

url = "https://api.euron.one/api/v1/euri/embeddings"

headers = {
    "Authorization": f"Bearer {api_key}",
    
    "Content-Type": "application/json",
}

payload = {
    "model": "text-embedding-3-small",
    "input": "my name is bhumika."
}

response = requests.post(url, headers=headers, json=payload)

print("Status:", response.status_code)
# print("Response:", response.text)

response.raise_for_status()

Status: 200


In [ ]:
# pip install requests
# !pip install python-dotenv

In [35]:
a = response.json()["data"][0]["embedding"]
len(response.json()["data"][0]["embedding"])  # 1536 dimensions in the embedding vector

1536

In [34]:
# the dimensions of the embedding vector depend on the model used. For text-embedding-3-small, it is 1536 dimensions.

In [53]:
url = "https://api.euron.one/api/v1/euri/embeddings"

headers = {
    "Authorization": f"Bearer {api_key}",
    
    "Content-Type": "application/json",
}

payload = {
    "model": "text-embedding-3-small",
    "input": "bhumika is a data scientist."
}

response = requests.post(url, headers=headers, json=payload)
b = response.json()["data"][0]["embedding"]

print("Status:", response.status_code)
# print("Response:", response.text)

response.raise_for_status()

Status: 200


In [37]:
len(b)

1536

In [54]:
headers = {
    "Authorization": f"Bearer {api_key}",
    
    "Content-Type": "application/json",
}

payload = {
    "model": "text-embedding-3-small",
    "input": "bhumika is learning generative AI."
}

response = requests.post(url, headers=headers, json=payload)
c = response.json()["data"][0]["embedding"]

print("Status:", response.status_code)
# print("Response:", response.text)

response.raise_for_status()

Status: 200


In [39]:
len(c)

1536

In [55]:
# a,b,c
url = "https://api.euron.one/api/v1/euri/embeddings"

headers = {
    "Authorization": f"Bearer {api_key}",
    
    "Content-Type": "application/json",
}

payload = {
    "model": "text-embedding-3-small",
    "input": "What bhumika is learning?"
}

response = requests.post(url, headers=headers, json=payload)
input = response.json()["data"][0]["embedding"]

print("Status:", response.status_code)
# print("Response:", response.text)

response.raise_for_status()

Status: 200


In [43]:
# a,b,c (assume its availble in vector db) , input(query)

import numpy as np

type(a)
a = np.array(a)
b = np.array(b)     
c = np.array(c)
input = np.array(input)


In [45]:
a,b,c,input

(array([ 0.04425049,  0.00057173, -0.01977539, ...,  0.02354431,
         0.0138855 ,  0.01244354]),
 array([ 3.05175781e-02, -8.09431076e-05,  5.91125488e-02, ...,
        -2.56729126e-03,  2.26440430e-02,  1.19628906e-02]),
 array([ 0.0164032 , -0.0211792 ,  0.06872559, ..., -0.01081085,
         0.02412415,  0.02290344]),
 array([ 0.02168274,  0.01182556,  0.05374146, ..., -0.00571442,
         0.00296211,  0.02186584]))

In [46]:
#distance between a and input, b and input, c and input
from numpy.linalg import norm

distance_a_input = norm(a - input)
distance_b_input = norm(b - input)
distance_c_input = norm(c - input)

In [51]:
distance_a_input
# distance_b_input
# distance_c_input

0.8242545747920988

In [49]:
distance_b_input

0.8124082222569022

In [50]:
distance_c_input

0.7798643819608355

In [ ]:
# a = "my name is bhumika."
# b = "bhumika is a data scientist."
# c = "bhumika is learning generative AI."
# input = "What bhumika is learning?"